/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
import { AmplifyConfig } from './types/amplify';

const awsmobile: AmplifyConfig = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:58aab270-a370-4aff-bfb9-fb2989a497a9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Tpo4WKclF",
    "aws_user_pools_web_client_id": "6rtqarrv8p7epcs658el65ekjf",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ziastfsexbcnffa6rvjqirxf3q.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://ziastfsexbcnffa6rvjqirxf3q.appsync-api.us-east-1.amazonaws.com/graphql",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "ainotejournal86b1c07be0df49a2b05ff1654917a035c187f-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};

export default awsmobile; 